import Head from "next/head";
import LandingPage from "../component/section1/section1";
import WireFrame from "../component/wireFrame/wireFrame";
import ScrollSection1 from "../component/scrollSection1/scrollSection1";
import ScrollSection2 from "../component/scrollSection2/scrollSection2";
import Footer from "../component/footer/footer";
import ScrollSection1Part3 from "../component/ui/scrollSection1Part3";

export default function Home() {
  return (
    <div>
      <Head>
        <title>LandingPage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <LandingPage />
      <WireFrame />
      <ScrollSection1 />
      <ScrollSection1Part3 />
      <ScrollSection2 />
      <Footer />
    </div>
  );
}
